### ISSUE TITLE
How to resolve the error ?

### ISSUE THREAD

**Issue by Andy766** [hcjohn463/JableTVDownload#1]
![image](https://user-images.githubusercontent.com/58882497/104120271-cba6a400-5335-11eb-88da-6d8598ffe7e3.png)

**Comment by hcjohn463** [comment]
![擷取](https://user-images.githubusercontent.com/45897386/104139547-3b289c00-53e7-11eb-8cf2-361393ab439a.PNG)

Try to put the dash behind your url :)

**Comment by Andy766** [comment]
![image](https://user-images.githubusercontent.com/58882497/104730608-a56c7400-573a-11eb-9ab7-6d448216ee2d.png)
I put the slash but the same error still occurred.

**Comment by hcjohn463** [comment]
![擷取](https://user-images.githubusercontent.com/45897386/104816366-a9d97f80-5855-11eb-89a0-49923de78bd2.PNG)

Sorry. I don't get this problem so I don't know how to help you.
My python version is 3.7 and environment is in windows.
