### ISSUE TITLE
下戴時間計算詢問

### ISSUE THREAD

**Issue by AndyKauo** [hcjohn463/JableTVDownload#27]
您好
感謝板主造福大家。 

1
想詢問剛開始下戴的"預計等待時間"是怎麼算的呢? 比如說是先假設某個網速算出來? 
一部片850mb花16.92分鐘，是預期的嗎?  想知道是不是我的網路問題(我的下戴200MB/上行40MB via speed test)

輸入jable網址:https://jable.tv/videos/adn-248/
開始下載 1139 個檔案..預計等待時間: **7.59 分鐘**視影片長度與網路速度而定)
當前下載: 788344.ts , 剩餘 1 個個  
**花費 16.92 分鐘** 爬取完成 !
開始合成影片..
花費 5.16 秒合成影片
下載完成!

2
另外我有下戴ffmpeg 放在main.py的目錄，但下戴下來後，發現我拖拉影片還是會卡
手動透過ffmpeg 轉檔後，拖拉時就不會卡，
ffmpeg -i ipx-486.mp4 -c:v libx264 -b:v 3M -threads 5 -preset superfast f_ipx-486.mp4

這也是預期行為嗎? 還是我一開始下戴時 並沒有吃到ffmpeg?

感謝大大

**Comment by hcjohn463** [comment]
1.我是照著自己電腦預估的 所以還是要看個人的網路速度~

2. 對 要手動用ffmpeg轉檔

**Comment by hcjohn463** [comment]
已更新重新上傳!
如果覺得好用 再麻煩你們幫忙按個星星
這樣搜尋才能到比較上面
有問題提出我都會繼續更新
大家一起讓世界更美好
謝謝你們~
