### ISSUE TITLE
RuntimeError: Sorry "firefox" browser was not found with a platform of "ios".

### ISSUE THREAD

**Issue by fufengwen** [hcjohn463/JableTVDownload#40]

**Comment by fufengwen** [comment]
挂了梯子后
Traceback (most recent call last):
  File "D:/Movie/JableTVDownload-main/main.py", line 47, in <module>
    m3u8url = result[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by fufengwen** [comment]
> 挂了梯子后
> Traceback (most recent call last):
> File "D:/Movie/JableTVDownload-main/main.py", line 47, in
> m3u8url = result[0]
> TypeError: 'NoneType' object is not subscriptable

debug后发现获取的网页中没有m3u8的内容，说明视频地址已经不再能获取到直链了，望作者测试下

**Comment by arthurzllu** [comment]
Read the discussion: https://github.com/hcjohn463/JableTVDownload/issues/30

**Comment by fufengwen** [comment]
> Read the discussion: #30

还是不太行，#30的方法都用过了，通过py抓到的网页一直都是please wait ...估计是被反爬虫了

**Comment by arthurzllu** [comment]
You should provide more information about the error you met.
