### ISSUE TITLE
不會操作，能出教學嗎?

### ISSUE THREAD

**Issue by Seikenn0630** [hcjohn463/JableTVDownload#65]
<img width="263" alt="螢幕擷取畫面 2022-02-14 011105" src="https://user-images.githubusercontent.com/99609280/153766339-cc15200d-f92d-463f-b48d-9cb127403372.png">

**Comment by learn2021-coder** [comment]
![image](https://user-images.githubusercontent.com/84202154/192559355-61f6bc8c-a4b1-4350-92f5-75b036bdc99f.png)

**Comment by learn2021-coder** [comment]
https://github.com/learn2021-coder/jabledownload-guide/blob/master/README.md
