### ISSUE TITLE
解决pycrypto和ssl认证问题

### ISSUE THREAD

**Issue by JarringBye** [hcjohn463/JableTVDownload#73]
在运行时出现两个问题 已解决：

1. 关于pycrypto问题
解决方式：
删除txt中pycryptodome那一行
之后手动`pip install pycryptodome`
2. 运行成功后，输入网址后报错：
`unable to get local issuer certificate (_ssl.c:1129) `
解决方式：main.py中添加如下：
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by yanggi** [comment]
成功的解决了我的问题，谢谢老哥

**Comment by clostou** [comment]
也遇到第一个问题。把pycryptodome更新到最新版本就行，作者要求的版本太低了。
