### ISSUE TITLE
影片編碼問題

### ISSUE THREAD

**Issue by Howard2306** [hcjohn463/JableTVDownload#8]
您好，我想請問一下你爬蟲下來的文件的影片編碼是什麼，
因為把影片匯入致 iTunes 時沒有反應(換句話說，就是匯入後沒有影片出現，但沒有出現錯誤)，
後來用轉檔的程式轉檔後就匯入就成功了！

如果把影片爬/載下來還需要再轉檔，可能會有點多此一舉！

謝謝

**Comment by hcjohn463** [comment]
您好：
謝謝您提出這個問題
已經在2021/5/20改成使用hevc來做影片的編碼
如果有問題的話請反應給我
感激不盡

**Comment by Howard2306** [comment]
感謝您的回覆！
對於影片編碼方面我也不太清楚，但我的轉檔程式是把爬下來的影片轉成AVC/H.264
而不是HEVC，可是卻能放入iTunes！

還有一件事是：您的程式爬下來的影片都能順利播放，但如果在播放器播放時，任意點選時間點時，影片的有些時間點會定住2~3秒才能夠繼續播放，有想過是不是網路的問題，但在爬影片時，速度都滿快的，沒有LAG的問題！

除此之外想問，您修改好後，我是否要重新下在你的code？

**Comment by hcjohn463** [comment]
> 感謝您的回覆！
> 對於影片編碼方面我也不太清楚，但我的轉檔程式是把爬下來的影片轉成AVC/H.264
> 而不是HEVC，可是卻能放入iTunes！
> 
> 還有一件事是：您的程式爬下來的影片都能順利播放，但如果在播放器播放時，任意點選時間點時，影片的有些時間點會定住2~3秒才能夠繼續播放，有想過是不是網路的問題，但在爬影片時，速度都滿快的，沒有LAG的問題！
> 
> 除此之外想問，您修改好後，我是否要重新下在你的code？

沒錯 這是因為下載下來的影片沒有經過轉檔
所以播放時才會有lag的問題
經過轉檔應該就可以解決

不知道您的GPU是不是Nvidia的 ?
因為測試發現跑轉檔的速度太慢
所以改成用硬體加速的方法實現轉檔
依賴的是NVIDIA的NVENC (GT 1030 等級含以上支援)

如果有的話 可以再重新下載一次code跑一遍
再麻煩您了 謝謝

**Comment by Howard2306** [comment]
了解 原來會LAG是因為沒有轉檔的緣故啊！

我的顯卡是AMD Radeon RXVEGA64 不曉得支不支援XD

**Comment by Howard2306** [comment]
> > 感謝您的回覆！
> > 對於影片編碼方面我也不太清楚，但我的轉檔程式是把爬下來的影片轉成AVC/H.264
> > 而不是HEVC，可是卻能放入iTunes！
> > 還有一件事是：您的程式爬下來的影片都能順利播放，但如果在播放器播放時，任意點選時間點時，影片的有些時間點會定住2~3秒才能夠繼續播放，有想過是不是網路的問題，但在爬影片時，速度都滿快的，沒有LAG的問題！
> > 除此之外想問，您修改好後，我是否要重新下在你的code？
> 
> 沒錯 這是因為下載下來的影片沒有經過轉檔
> 所以播放時才會有lag的問題
> 經過轉檔應該就可以解決
> 
> 不知道您的GPU是不是Nvidia的 ?
> 因為測試發現CPU跑轉檔的速度太慢
> 所以改成用硬體加速的方法實現轉檔
> 依賴的是NVIDIA的NVENC (GT 1030 等級含以上支援)
> 
> 如果有的話 可以再重新下載一次code跑一遍
> 再麻煩您了 謝謝

123

**Comment by hcjohn463** [comment]
> 了解 原來會LAG是因為沒有轉檔的緣故啊！
> 
> 我的顯卡是AMD Radeon RXVEGA64 不曉得支不支援XD

考量到會有AMD和NVIDIA兩大族群的緣由
現在改成使用多執行緒CPU來做轉檔了
謝謝您提出問題 👍

**Comment by Howard2306** [comment]
想請問是AMD不支援嗎

> > 了解 原來會LAG是因為沒有轉檔的緣故啊！
> > 我的顯卡是AMD Radeon RXVEGA64 不曉得支不支援XD
> 
> 考量到會有AMD和NVIDIA兩大族群的緣由
> 現在改成使用多執行緒CPU來做轉檔了
> 謝謝您提出問題 👍

想請問是因為AMD沒有硬體加速的套件嗎?
若用CPU來轉檔，速度會不會差很多？

感謝您的修改！

**Comment by hcjohn463** [comment]
> 想請問是因為AMD沒有硬體加速的套件嗎?
> 若用CPU來轉檔，速度會不會差很多？
> 
> 感謝您的修改！

最近幾年的GPU都有支援硬體加速
只是我手邊沒有AMD的顯卡
所以沒辦法測試 🥴


我的電腦GPU使用的是gtx1060
速度應該有差個2~3倍

如果您想使用GPU加速的話
可以藉由修改encode.py裡的ffmpeg參數
來執行硬體的加速

**Comment by Howard2306** [comment]
> > 想請問是因為AMD沒有硬體加速的套件嗎?
> > 若用CPU來轉檔，速度會不會差很多？
> > 感謝您的修改！
> 
> 最近幾年的GPU都有支援硬體加速
> 只是我手邊沒有AMD的顯卡
> 所以沒辦法測試 🥴
> 
> 我的電腦GPU使用的是gtx1060
> 速度應該有差個2~3倍
> 
> 如果您想使用GPU加速的話
> 可以藉由修改encode.py裡的ffmpeg參數
> 來執行硬體的加速

了解
剛剛拿新的code試抓影片
log出現以下問題

> 

`Traceback(most recent call last):
  File "main.py", line 131, in <module>
    encodeMp4(folderPath)
  File "E:\JableTVDownload-main\encode.py", line 19, in encodeMp4
    ffmpeg
  File "E:\Python387\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "E:\Python387\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "E:\Python387\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Python387\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。`

但影片好像能正常播放XD 所以想請問是什麼問題

**Comment by hcjohn463** [comment]
> 了解
> 剛剛拿新的code試抓影片
> log出現以下問題
> 
> > 
> 
> `Traceback(most recent call last): File "main.py", line 131, in <module> encodeMp4(folderPath) File "E:\JableTVDownload-main\encode.py", line 19, in encodeMp4 ffmpeg File "E:\Python387\lib\site-packages\ffmpeg\_run.py", line 313, in run process = run_async( File "E:\Python387\lib\site-packages\ffmpeg\_run.py", line 284, in run_async return subprocess.Popen( File "E:\Python387\lib\subprocess.py", line 854, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "E:\Python387\lib\subprocess.py", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系統找不到指定的檔案。`
> 
> 但影片好像能正常播放XD 所以想請問是什麼問題
> 對了番號前面名字有出現o，表示它沒轉成功吧？

對 這是沒有轉成功 
因為要事先安裝 [FFmpeg ](https://www.ffmpeg.org/) 才能進行轉檔
忘記說了不好意思

**Comment by Howard2306** [comment]
> > 了解
> > 剛剛拿新的code試抓影片
> > log出現以下問題
> > > 
> > 
> > 
> > `Traceback(most recent call last): File "main.py", line 131, in <module> encodeMp4(folderPath) File "E:\JableTVDownload-main\encode.py", line 19, in encodeMp4 ffmpeg File "E:\Python387\lib\site-packages\ffmpeg\_run.py", line 313, in run process = run_async( File "E:\Python387\lib\site-packages\ffmpeg\_run.py", line 284, in run_async return subprocess.Popen( File "E:\Python387\lib\subprocess.py", line 854, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "E:\Python387\lib\subprocess.py", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系統找不到指定的檔案。`
> > 但影片好像能正常播放XD 所以想請問是什麼問題
> > 對了番號前面名字有出現o，表示它沒轉成功吧？
> 
> 對 這是沒有轉成功
> 因為要事先安裝 [FFmpeg ](https://www.ffmpeg.org/) 才能進行轉檔
> 忘記說了不好意思

![image](https://user-images.githubusercontent.com/56557271/118979536-25397200-b9ab-11eb-85a4-c0b46cb83fde.png)
請問一下是下載哪一個，還是都可以！

目前還是程式新手，想請教一下硬件加速是指DXVA嗎？我剛Google很多資料發現N卡是用Cuda去做，不知道我的理解對不對！
至於AMD就查不太到，想請問有什麼關鍵字可以去搜尋AMD相關的硬件加速，或是只要在ffmpeg裡面加什麼參數就好，想試試看怎麼修改code！

**Comment by hcjohn463** [comment]
1. [安裝ffmpeg教學 ](https://annkuoq.github.io/blog/2019-12-17-install-ffmpeg/)
2. [Different h264 encoders in FFmpeg](https://stackoverflow.com/questions/50693934/different-h264-encoders-in-ffmpeg)

**Comment by Howard2306** [comment]
> > ![image](https://user-images.githubusercontent.com/56557271/118979536-25397200-b9ab-11eb-85a4-c0b46cb83fde.png)
> > 請問一下是下載哪一個，還是都可以！
> > 目前還是程式新手，想請教一下硬件加速是指DXVA嗎？我剛Google很多資料發現N卡是用Cuda去做，不知道我的理解對不對！
> > 至於AMD就查不太到，想請問有什麼關鍵字可以去搜尋AMD相關的硬件加速，或是只要在ffmpeg裡面加什麼參數就好，想試試看怎麼修改code！
> 
> 1. [安裝ffmpeg教學 ](https://annkuoq.github.io/blog/2019-12-17-install-ffmpeg/)
> 2. [Different h264 encoders in FFmpeg](https://stackoverflow.com/questions/50693934/different-h264-encoders-in-ffmpeg)

感謝您！
請問關於下載ffmpeg 是指要另外下載還是指python套件載就好？

**Comment by hcjohn463** [comment]
> 感謝您！
> 請問關於下載ffmpeg 是指要另外下載還是指python套件載就好？

原本在requirements就已經安裝ffmpeg的套件了 不用再額外裝
但要讓它能使用還是需要去官網安裝FFmpeg
才能讓cpu執行轉檔喔

**Comment by Howard2306** [comment]
> > 感謝您！
> > 請問關於下載ffmpeg 是指要另外下載還是指python套件載就好？
> 
> 原本在requirements就已經安裝ffmpeg用於python的API了
> 所以不用再額外裝
> 但要讓它能使用還是需要去官網安裝FFmpeg
> 才能讓CPU & GPU執行轉檔喔

您好轉成功了 但遇到一個問題是影片爬下來的容量變很大
原本可能為1~2G，結果變成了4G多，然後轉換後更變成了9G
想請問為什麼會發生這種狀況

**Comment by Howard2306** [comment]
另外可否請教一下如果您是用Nvidia GPU 進行加速  想請問您的參數是怎麼設定的

**Comment by Howard2306** [comment]
> 可否請教一下如果您是用Nvidia GPU 進行加速 想請問您的參數是怎麼設定的
> 爬了很多文，我是透過CMD用ffmpeg去轉的，您 python 參數中`C:V`這個設定我在網路上google到的內容
> 他們是在CMD下 `-c:v` 想了解有什麼差異？
